import gym
env = gym.make('Go9x9-v0')
env.reset()
env.render()
observation, reward, done, info = env.step(10)

print("")
print("observation")
print(observation)
print("")
print("reward")
print(reward)
print("")
print("done")
print(done)
print("")
print("info")
print(info)

env.render()
env.step(14)
env.render()
observation, reward, done, info = env.step(10)
env.render()


print("")
print("observation")
print(observation)
print("")
print("reward")
print(reward)
print("")
print("done")
print(done)
print("")
print("info")
print(info)